In [80]:
import numpy as np

train_count = 1027
wc = 1

h = np.ones((train_count, wc), dtype=float)
train_label = np.ones(train_count, dtype=float)

In [81]:
h*=3

In [82]:
train_label.reshape(train_count, 1)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [84]:
delta=10**(-9)
def loss_function(t, y):
    return -np.sum(t*np.log(y+delta) + (1-t)*np.log(1-y+delta)) 

In [85]:
loss_function(train_label.reshape(train_count, 1), h)

C:\Users\JJy\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


nan

In [86]:
tr_label = train_label.reshape(train_count, 1)

In [87]:
loss_function(tr_label, h) / 1027

C:\Users\JJy\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


nan

In [88]:
a = h - tr_label

In [89]:
type(a)

numpy.ndarray

In [90]:
uc = 50

In [91]:
a = np.ones((train_count, uc), dtype=float)

In [92]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [93]:
b1 = np.random.rand(uc)

In [94]:
b1

array([0.44152604, 0.73200285, 0.26381071, 0.56080601, 0.5526321 ,
       0.46081095, 0.07180607, 0.88135528, 0.45964127, 0.49656604,
       0.35267624, 0.35524413, 0.65713008, 0.88459777, 0.80562372,
       0.52115579, 0.12742983, 0.90417236, 0.64793906, 0.9782942 ,
       0.48130994, 0.63611241, 0.95380543, 0.67377538, 0.02875036,
       0.42346033, 0.38705286, 0.63123449, 0.95007649, 0.82794412,
       0.78826122, 0.64469492, 0.31407818, 0.42390183, 0.90317591,
       0.99951188, 0.43596308, 0.37566603, 0.59298612, 0.59941348,
       0.21235952, 0.68595333, 0.91000576, 0.17187713, 0.4236861 ,
       0.72996114, 0.619821  , 0.2547801 , 0.07495061, 0.60151965])

In [95]:
a + b1

array([[1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965],
       [1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965],
       [1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965],
       ...,
       [1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965],
       [1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965],
       [1.44152604, 1.73200285, 1.26381071, ..., 1.2547801 , 1.07495061,
        1.60151965]])

In [96]:
h*=3
loss3 = h - tr_label

In [97]:
loss3

array([[8.],
       [8.],
       [8.],
       ...,
       [8.],
       [8.],
       [8.]])

In [98]:
(1 * np.mean(loss3, axis=0)).shape

(1,)

In [99]:
b3 = np.random.rand(wc)

In [100]:
b3.shape

(1,)

In [101]:
b1 = np.random.rand(uc)

In [102]:
b1*0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
training_loss = np.sum(np.abs(tr_label- h) > 0.5)

In [104]:
training_loss

1027

In [105]:
np.abs(tr_label- h) 

array([[8.],
       [8.],
       [8.],
       ...,
       [8.],
       [8.],
       [8.]])